name = "hex-gfq-mathlib"
defaultTargets = ["HexGFqMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGFq"
git = "https://github.com/leanprover/hex-gfq.git"
rev = "254f036a730d8fb60525c21715cd6e5182f3ff89"

[[require]]
name = "HexGF2Mathlib"
git = "https://github.com/leanprover/hex-gf2-mathlib.git"
rev = "431a8d06d244a8166c8e3dae89d377c9516cfeae"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexGFqMathlib"
