name = "hex-gfq-mathlib"
defaultTargets = ["HexGFqMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGFq"
git = "https://github.com/leanprover/hex-gfq.git"
rev = "5e1baffd4cae1e35e3fd2b7be52550b5ded39663"

[[require]]
name = "HexGF2Mathlib"
git = "https://github.com/leanprover/hex-gf2-mathlib.git"
rev = "0bc9d2ee3087e7a3a717d22951bb3a36e90731ad"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[require]]
name = "HexConway"
git = "https://github.com/leanprover/hex-conway.git"
rev = "ac73121a6e51171833943afae02fc41233797707"

[[require]]
name = "HexModArithMathlib"
git = "https://github.com/leanprover/hex-mod-arith-mathlib.git"
rev = "7a6dee3107b13b1f0cabfbdec99b0c3329881245"

[[require]]
name = "HexPolyFpMathlib"
git = "https://github.com/leanprover/hex-poly-fp-mathlib.git"
rev = "6e589eed50000bfd1354c955ef940fcf7df02f72"

[[lean_lib]]
name = "HexGFqMathlib"
