name = "hex-gfq-mathlib"
defaultTargets = ["HexGFqMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGFq"
git = "https://github.com/leanprover/hex-gfq.git"
rev = "b39778269bcb39ea561e760266ed15165586b3a3"

[[require]]
name = "HexGF2Mathlib"
git = "https://github.com/leanprover/hex-gf2-mathlib.git"
rev = "64df28468d4dd3574161696dae53079584b31f69"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexGFqMathlib"
